linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - lll
    - maligned
    - scopelint
    - stylecheck
    - unparam
  exclude:
    - "not declared by package utf8"
    - "unicode/utf8/utf8.go"
